version: '3.8'

services:

  laravel_app:
    image: ghcr.io/youssefat928/elm-partnershipautomation-app:latest
    container_name: laravel_app
    working_dir: /var/www/html
    restart: always
    # DO NOT mount the entire project, it destroys "vendor"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    # If you want .env inside container:
    env_file:
      - .env

  laravel_nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public   # Only expose public/ folder to nginx
    depends_on:
      - laravel_app
